os: Visual Studio 2015

clone_depth: 1

init:
  - call call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set PATH=%PATH%;C:\cygwin\bin;

build_script:
  - set MRUBY_CONFIG=appveyor_config.rb
  - ruby .\minirake test
