os: Visual Studio 2015

clone_depth: 1

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      machine: amd64

    # Visual Studio 2010 32bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat
      machine: x86
init:
  - call "%visualcpp%" %machine%
  - set PATH=%PATH%;C:\cygwin\bin;

build_script:
  - set MRUBY_CONFIG=appveyor_config.rb
  - ruby .\minirake test
